# Generated by Django 3.0.14 on 2023-06-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_auto_20230629_0948'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='docente',
            table='Docente',
        ),
    ]
